package com.lightningsports.VictronBatteryMonitor;

/**
 * Created by r_koller on 10/27/2025.
 */
public enum VictronCode {
    ID_PRODUCT_ID(0x0100),
    ID_PRODUCT_REVISION(0x0101),
    ID_SERIAL_NUMBER(0x010A),
    ID_MODEL_NUMBER(0x010B),
    ID_DESCRIPTION(0x010C),
    ID_UP_TIME(0x0120),
    ID_BLUETOOTH(0x0150),
    ID_MAIN_VOLTAGE(0xED8D),
    ID_AUX_VOLTAGE(0xED7D),
    ID_CURRENT(0xED8F),
    ID_POWER(0xED8E),
    ID_CONSUMED_AH(0xEEFF),
    ID_SOC(0x0FFF),
    ID_TIME_TO_GO(0x0FFE),
    ID_TEMPERATURE(0xEDEC),
    ID_MID_POINT_VOLTAGE(0x0382),
    ID_MID_POINT_VOLTAGE_DEV(0x0383),
    ID_SYNCHRONIZATION_STATE(0xEEB6),
    ID_DEPTH_DEEPEST_DISCHARGE(0x0300),
    ID_DEPTH_LATEST_DISCHARGE(0x0301),
    ID_DEPTH_AVERAGE_DISCHARGE(0x0302),
    ID_NUMBER_CYCLES(0x0303),
    ID_NUMBER_FULL_DISCHARGE(0x0304),
    ID_CUMULATIVE_AMP_HOURS(0x0305),
    ID_MINIMUM_VOLTAGE(0x0306),
    ID_MAXIMUM_VOLTAGE(0x0307),
    ID_SECONDS_SINCE_FULL_CHARGE(0x0308),
    ID_NUMBER_AUTOMATIC_SYNCHRONIZATIONS(0x0309),
    ID_NUMBER_LOW_VOLTAGE_ALARMS(0x030A),
    ID_NUMBER_HIGH_VOLTAGE_ALARMS(0x030B),
    ID_MINIMUM_STARTER_VOLTAGE(0x030E),
    ID_MAXIMUM_STARTER_VOLTAGE(0x030F),
    ID_PRODUCED_ENERGY(0x0310),
    ID_CONSUMED_ENERGY(0x0311),
    ID_BATTERY_CAPACITY(0x1000),
    ID_CHARGED_VOLTAGE(0x1001),
    ID_TAIL_CURRENT(0x1002),
    ID_CHARGED_DETECTION_TIME(0x1003),
    ID_CHARGE_EFFICIENCY(0x1004),
    ID_PEUKERT_COEFFICIENT(0x1005),
    ID_CURRENT_THRESHOLD(0x1006),
    ID_TIME_TO_GO_DELTA_T(0x1007),
    ID_DISCHARGE_FLOOR(0x1008),
    ID_RELAY_LOW_SOC_CLEAR(0x1009),
    ID_USER_CURRENT_ZERO(0x1034),
    ID_ALARM_BUZZER(0xEEFC),
    ID_ALARM_LOW_VOLTAGE(0x0320),
    ID_ALARM_LOW_VOLTAGE_CLEAR(0x0321),
    ID_ALARM_HIGH_VOLTAGE(0x0322),
    ID_ALARM_HIGH_VOLTAGE_CLEAR(0x0323),
    ID_ALARM_LOW_STARTER(0x0324),
    ID_ALARM_LOW_STARTER_CLEAR(0x0325),
    ID_ALARM_HIGH_STARTER(0x0326),
    ID_ALARM_HIGH_STARTER_CLEAR(0x0327),
    ID_ALARM_LOW_SOC(0x0328),
    ID_ALARM_LOW_SOC_CLEAR(0x0329),
    ID_ALARM_LOW_TEMP(0x032A),
    ID_ALARM_LOW_TEMP_CLEAR(0x032B),
    ID_ALARM_HIGH_TEMP(0x032C),
    ID_ALARM_HIGH_TEMP_CLEAR(0x032D),
    ID_ALARM_MID_VOLTAGE(0x0331),
    ID_ALARM_MID_VOLTAGE_CLEAR(0x0332),
    ID_ALARM_ACKNOWLEDGE(0x031F),
    ID_RELAY_MODE(0x034F),
    ID_RELAY_INVERT(0x034D),
    ID_RELAY_STATE_CONTROL(0x034E),
    ID_RELAY_MINIMAL_ENABLE_TIME(0x100A),
    ID_RELAY_DISABLE_TIME(0x100B),
    ID_RELAY_LOW_VOLTAGE(0x0350),
    ID_RELAY_LOW_VOLTAGE_CLEAR(0x0351),
    ID_RELAY_HIGH_VOLTAGE(0x0352),
    ID_RELAY_HIGH_VOLTAGE_CLEAR(0x0353),
    ID_RELAY_LOW_STARTER(0x0354),
    ID_RELAY_LOW_STARTER_CLEAR(0x0355),
    ID_RELAY_HIGH_STARTER(0x0356),
    ID_RELAY_HIGH_STARTER_CLEAR(0x0357),
    ID_RELAY_LOW_TEMP(0x035A),
    ID_RELAY_LOW_TEMP_CLEAR(0x035B),
    ID_RELAY_HIGH_TEMP(0x035C),
    ID_RELAY_HIGH_TEMP_CLEAR(0x035D),
    ID_RELAY_MID_VOLTAGE(0x0361),
    ID_RELAY_MID_VOLTAGE_CLEAR(0x0362),
    ID_DISPLAY_BACKLIGHT_INTENSITY(0xEEFE),
    ID_DISPLAY_BACKLIGHT_ALWAYS_ON(0x0400),
    ID_DISPLAY_SCROLL_SPEED(0xEEF5),
    ID_DISPLAY_SHOW_VOLTAGE(0xEEE0),
    ID_DISPLAY_SHOW_AUX_VOLTAGE(0xEEE1),
    ID_DISPLAY_SHOW_MID_VOLTAGE(0xEEE2),
    ID_DISPLAY_SHOW_CURRENT(0xEEE3),
    ID_DISPLAY_SHOW_CONSUMED_AH(0xEEE4),
    ID_DISPLAY_SHOW_SOC(0xEEE5),
    ID_DISPLAY_SHOW_TIME_TO_GO(0xEEE6),
    ID_DISPLAY_SHOW_TEMPERATURE(0xEEE7),
    ID_DISPLAY_SHOW_POWER(0xEEE8),
    ID_MISC_SOFTWARE_VERSION(0xEEF9),
    ID_MISC_SETUP_LOCK(0xEEF6),
    ID_MISC_SHUNT_AMPS(0xEEFB),
    ID_MISC_SHUNT_VOLTS(0xEEFA),
    ID_MISC_TEMPERATURE_UNITS(0xEEF7),
    ID_MISC_TEMPERATURE_COEFFICIENT(0xEEF4),
    ID_MISC_AUX_INPUT(0xEEF8),
    ID_MISC_START_SYNCHRONIZED(0xEEFD),
    ID_MISC_SETTINGS_CHANGED_TIMESTAMP(0xEC41),
    ID_MISC_BLUETOOTH_MODE(0x0090),
    ID_MISC_DC_MONITOR_MODE(0xEEB8),
    ID_ALARM_REASON(0x03F1),  //Not Victron Native Added to accommodate the historic feed
    ID_MINIMUM_AUX_VOLTAGE(0x03F2),  //Not Victron Native Added to accommodate the historic feed
    ID_MAXIMUM_AUX_VOLTAGE(0x03F3),  //Not Victron Native Added to accommodate the historic feed
    ID_CHECKSUM(0x03F4);  //Not Victron Native Added to accommodate the historic feed


    private final int code;

    VictronCode(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }

    public static VictronCode fromCode(int code) {
        for (VictronCode status : VictronCode.values()) {
            if (status.getCode() == code) {
                return status;
            }
        }
        throw new IllegalArgumentException("Invalid status code: " + code);
    }

    public static VictronCode fromValue(String value) {
        for (VictronCode status: VictronCode.values()) {
            if (status.name().compareTo(value)==0)
                return status;
        }
        throw new IllegalArgumentException("Invalid status value: " + value);
    }
}
